version: "3.8"

services:
  bot:
    build: .
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
